/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  theme: { extend: {} },
  plugins: [],
  safelist: [
    'bg-gray-900',
    'text-white',
    'text-gray-300',
    'text-gray-400',
    'text-yellow-400',
    'text-red-400',
    'text-blue-400',
    'bg-gray-800',
    'bg-gray-700',
    'bg-gray-600',
    'bg-blue-500',
    'bg-blue-600',
    'bg-yellow-500',
    'bg-yellow-600',
    'bg-green-500',
    'bg-green-600',
    'bg-red-500',
    'bg-red-600',
    'bg-gray-500',
    'bg-gray-600',
    'max-w-4xl',
    'mx-auto',
    'min-h-screen',
    'p-4',
    'px-4',
    'sm:px-4',
    'rounded-lg',
    'mb-4',
    'flex',
    'space-x-2',
    'space-x-4',
    'space-y-2',
    'text-xl',
    'font-semibold',
    'font-bold',
    'text-sm',
    'list-disc',
    'pl-6',
    'w-full',
    'h-4',
    'flex-1',
    'mr-2',
    'justify-between',
    'items-center',
    'text-lg',
    'w-20'
  ]
}
